# Generated by Django 4.0.3 on 2022-03-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='qwerty', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='qwerty', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
