# Generated by Django 4.0.3 on 2022-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(default='/some-default-link', max_length=500),
            preserve_default=False,
        ),
    ]
