# Generated by Django 4.0.3 on 2022-03-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_upvotes_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='post',
            new_name='article',
        ),
    ]
